// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcMSvDosB6vPs6Nx8wePvbZ_2CpLBanmE',
    appId: '1:610705749488:web:9aa3a485a108e81bda9935',
    messagingSenderId: '610705749488',
    projectId: 'vk-shop-4e316',
    authDomain: 'vk-shop-4e316.firebaseapp.com',
    storageBucket: 'vk-shop-4e316.firebasestorage.app',
    measurementId: 'G-R6KSPPWFVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_6JuFPqKQpJKguRyRfQFJoBlorfhDtC4',
    appId: '1:610705749488:android:8d36f4a54d0a0752da9935',
    messagingSenderId: '610705749488',
    projectId: 'vk-shop-4e316',
    storageBucket: 'vk-shop-4e316.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyA3La372W3pMCgq8X13vx_c6ETOklR-c',
    appId: '1:610705749488:ios:fe6d71380d5624e2da9935',
    messagingSenderId: '610705749488',
    projectId: 'vk-shop-4e316',
    storageBucket: 'vk-shop-4e316.firebasestorage.app',
    iosBundleId: 'com.example.vkShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyA3La372W3pMCgq8X13vx_c6ETOklR-c',
    appId: '1:610705749488:ios:fe6d71380d5624e2da9935',
    messagingSenderId: '610705749488',
    projectId: 'vk-shop-4e316',
    storageBucket: 'vk-shop-4e316.firebasestorage.app',
    iosBundleId: 'com.example.vkShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcMSvDosB6vPs6Nx8wePvbZ_2CpLBanmE',
    appId: '1:610705749488:web:b02dba564e2556bdda9935',
    messagingSenderId: '610705749488',
    projectId: 'vk-shop-4e316',
    authDomain: 'vk-shop-4e316.firebaseapp.com',
    storageBucket: 'vk-shop-4e316.firebasestorage.app',
    measurementId: 'G-N4JMRE0EBP',
  );
}
